/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automatedparkingsystem;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author LENOVO
 */
public class SplashScreen extends javax.swing.JFrame implements CustomPanel.ProgressBarInterface {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
        jp_progress.pbr = this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_progress = new automatedparkingsystem.CustomPanel();
        main_run = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jp_progress.setBackground(new java.awt.Color(0, 204, 204));
        jp_progress.setLayout(null);

        main_run.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        main_run.setText("Welcome to Automated Public Parking System!");
        main_run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                main_runActionPerformed(evt);
            }
        });
        jp_progress.add(main_run);
        main_run.setBounds(80, 340, 410, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automatedparkingsystem/BG.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jp_progress.add(jLabel1);
        jLabel1.setBounds(-6, -6, 580, 390);

        getContentPane().add(jp_progress);
        jp_progress.setBounds(0, 0, 570, 390);

        setSize(new java.awt.Dimension(568, 385));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void main_runActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_main_runActionPerformed
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int num = 1; num <= 100; num++) {
                    try {
                        jp_progress.UpdateProgress(num);
                        jp_progress.repaint();
                        Thread.sleep(50);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(SplashScreen.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }

            }
        }).start();

    }//GEN-LAST:event_main_runActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private automatedparkingsystem.CustomPanel jp_progress;
    private javax.swing.JButton main_run;
    // End of variables declaration//GEN-END:variables

    @Override
    public void OnProgressComplete() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                main_run.setVisible(false);
                SplashScreen s = new SplashScreen();
                s.setVisible(false);
                HomePage h = new HomePage();
                h.setVisible(true);
            }
        }).start();

    }
}
